{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DataSourceConnection\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DataSourceConnection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4023462b-34e3-4481-98c1-9c8e92d9443d",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "neighbourhood",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a5aa09d-92a6-4ae3-84ef-c5cd764caa67",
            "sourceColumn": "neighbourhood",
            "summarizeBy": "none"
          },
          {
            "name": "latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "45993621-674e-4108-868c-a88e0b87f5a7",
            "sourceColumn": "latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "db462288-3f76-4647-aa96-3c7b808cac5e",
            "sourceColumn": "longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "room_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44ddb1c1-4298-4b19-ac21-6c6fca022578",
            "sourceColumn": "room_type",
            "summarizeBy": "none"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68482951-b62d-4876-b2ab-3d39a1cf32d6",
            "sourceColumn": "price",
            "summarizeBy": "sum"
          },
          {
            "name": "days_occupied_in_2019",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f91ed56f-e8ac-4943-a1f4-d0fff80e4fac",
            "sourceColumn": "days_occupied_in_2019",
            "summarizeBy": "sum"
          },
          {
            "name": "minimum_nights",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e39410fa-498d-47ab-9c29-ded39d633911",
            "sourceColumn": "minimum_nights",
            "summarizeBy": "sum"
          },
          {
            "name": "number_of_reviews",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70497fbf-2c57-4892-8078-745d9aa9d015",
            "sourceColumn": "number_of_reviews",
            "summarizeBy": "sum"
          },
          {
            "name": "reviews_per_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff0028bb-75de-4792-9907-c3640d04d7e9",
            "sourceColumn": "reviews_per_month",
            "summarizeBy": "sum"
          },
          {
            "name": "availability_2020",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a4d73ae-c3a5-4657-87d5-1bf64e8698a9",
            "sourceColumn": "availability_2020",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "93bc7726-271e-44bd-b016-af38c6f6104f",
        "partitions": [
          {
            "name": "DataSourceConnection",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"c:\\users\\matin.omarov\\desktop\\projects\\test\\new_york.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"id\", Int64.Type}, {\"neighbourhood\", type text}, {\"latitude\", type number}, {\"longitude\", type number}, {\"room_type\", type text}, {\"price\", Int64.Type}, {\"days_occupied_in_2019\", Int64.Type}, {\"minimum_nights\", Int64.Type}, {\"number_of_reviews\", Int64.Type}, {\"reviews_per_month\", type number}, {\"availability_2020\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}